import type { Driver, Status } from '../types';

const rawData = `1	DIKI SAPUTRA	HANVAN XCMG 51	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N
2	M. ZAINATUL AGUNG	HANVAN XCMG 51	D	D	D	D	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N	N	N	N	N	N	OFF	D	D	D	D
3	M. NORMAN HAKIM	HANVAN XCMG 55	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N
4	VIKI LIANDI	HANVAN XCMG 55	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF
5	HERMINTO. R	DT HANVAN 98	N	N	N	N	N	OFF	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	N	N	N	N	N	OFF	D	D
6	BINTARA PRIYANDI	DT HANVAN 98	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N	OFF	D	D	D	D	D	N	N
7	RIDHO ILLAFI SUKMA	DT HANVAN 99	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D
8	RUDI HARTONO	DT HANVAN 99	CR	CR	CR	CR	I	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N	N	N
9	TOUPIT ASMAN	DT HANVAN 100	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR
10	ADIANTO	DT HANVAN 100	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D
11	TENGGO NOVRIAN	DT HANVAN 101	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N
12	MINAL BAHRI	DT HANVAN 101	D	D	D	N	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N	N	N	N	N	OFF	D	D
13	GUNDALA	DT HANVAN 102	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D
14	FITRI ARYA PUTRA	DT HANVAN 102	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N
15	ADE KURNIAWAN	DT HANVAN 103	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D
16	NANDA NOVIANDI	DT HANVAN 103	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N
17	KELVIN PRANATA	DT HANVAN 104	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N
18	FERI ANGGRIAWAN	DT HANVAN 104	D	D	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N	N	N	N	N	N	N	OFF	D	D	D	D	D
19	OWEN RAHMADANI MAHENDRA	DT HANVAN 105	N	N	N	OFF	D	D	D	D	D	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N	N	N	N	N	N	OFF
20	DODI CANDRA	DT HANVAN 105	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	N
21	SANDRA HALIYA PUTRA	DT HANVAN 188	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D
22	ALEX TORNANDO	DT HANVAN 188	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N
23	SUMARTO	DT HANVAN 189	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF
24	MUJI SATRIA NOTO SUSENO	DT HANVAN 189	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D
25	UCI PURWANTO	DT HANVAN 190	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N
26	DODI PRAYOGI	DT HANVAN 190	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	CR	CR	CR	CR	CR	CR	CR	CR
27	DOLI INDRA	DT HANVAN 191	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	CR	CR	CR	CR	CR	CR
28	FERRY ADRIAN	DT HANVAN 191	D	D	D	D	D	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N	N	N	OFF	D	D	D
29	EGI WIRANTO	DT HANVAN 192	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D
30	WAHYU IMAM MAULANA	DT HANVAN 192	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N
31	ARIA DEBIANTO TARIGAN	DT HANVAN 193	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D
32	HARIONO	DT HANVAN 193	N	N	N	N	N	OFF	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	N	N	N
33	SADAM HUSEN	DT HANVAN 194	D	D	D	D	N	N	N	N	N	OFF	D	D	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N
34	GUNAWAN MAHENDRA	DT HANVAN 194	N	N	N	OFF	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	N	N	N	N	N	OFF	D	D
35	HERMAN SAPUTRA	DT HANVAN 195	OFF	D	D	D	D	D	D	D	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	N	N	N	N	N
36	EGI APRILI MARTA	DT HANVAN 195	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D
37	FAREL ANANDA PARINDRA	DT HANVAN 196	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N
38	PERISTIAWAN	DT HANVAN 196	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I
39	SUGIHARTO	DT HANVAN 197	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D
40	JONI ARDILES	DT HANVAN 197	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N
41	YOPI ILHAMI	DT HANVAN 198	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N
42	PURWOKO	DT HANVAN 198	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D
43	AL ZONIKA	DT HANVAN 199	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D
44	M. ILHAM SURYA WARDANA LUMY	DT HANVAN 199	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	CR	CR	CR	CR	CR	CR
45	CHARLES BILLANDIS	DT HANVAN 200	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF
46	REDI SYAPUTRA	DT HANVAN 200	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D
47	MUHAMMAD FAJAR AFIKI	DT HANVAN 201	D	D	N	N	N	N	N	N	OFF	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	N	N
48	AGAM PRAYUDI	DT HANVAN 201	CR	CR	CR	CR	CR	CR	I	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D
49	RISKY TRY UTANI	DT HANVAN 202	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D
50	SETIA BUDI	DT HANVAN 202	N	N	OFF	D	D	D	D	D	D	D	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	N	N	N	N
51	ASMAREKI	DT HANVAN 203	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N
52	IRFAN ARIANDI	DT HANVAN 203	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D
53	ENGKI PANHOTEN	DT HANVAN 204	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D
54	ANDI PRADANA	DT HANVAN 204	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N
55	PANCA SUKMA WARDI	DT HANVAN 205	OFF	D	D	D	D	D	D	D	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D
56	EKO RIZALDI	DT HANVAN 205	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N
57	WAHYU RAMADAN	DT HANVAN 206	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N
58	ROBBY NANDA SYAPUTRA	DT HANVAN 206	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D
59	HARMANCA	DT HANVAN 207	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D
60	DESRIANTO	DT HANVAN 207	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N
61	M. RIZKI AKBAR	DT HANVAN 208	CR	CR	CR	I	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N
62	ANDIANSYAH	DT HANVAN 208	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D
63	IWAN LUBIS	DT HANVAN 209	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D
64	IWEN OGILVI SAPUTRA	DT HANVAN 209	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR
65	DEPRIWAN	DT HANVAN 210	N	N	OFF	D	D	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N	N	N	N	N	N	N	OFF
66	REDO ILAHI	DT HANVAN 210	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	OFF	D	D	D	D	D	D	CR
67	RINALDI	DT HANVAN 211	CR	I	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	OFF	D	D
68	APRIANDA MUTIYOVA	DT HANVAN 211	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR
69	MHD ROZALI	DT HANVAN 212	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D
70	SUYONO. P	DT HANVAN 212	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I
71	YOGI DIKA PUTRA	DT HANVAN 213	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N
72	HADIANTO	DT HANVAN 213	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D
73	YAN ALBERT	DT HANVAN 214	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D
74	GUSTI MAHENDRA	DT HANVAN 214	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	CR	CR	CR
75	ZULFAHMI	DT HANVAN 215	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D
76	LUKMAN HAKIM ICHWAN	DT HANVAN 215	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR
77	SUDARSO	DT HANVAN 216	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N
78	ARI WIBOWO	DT HANVAN 216	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D
79	AGRI DASLINO PRATAMA	DT HANVAN 217	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D
80	HERCULES	DT HANVAN 217	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N
81	ERIK USTRANI	DT HANVAN 218	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR
82	ANDRE HASKOPER	DT HANVAN 218	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N
83	CANDRA INDRA	DT HANVAN 219	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N
84	PALMA	DT HANVAN 219	CR	CR	I	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D
85	ADI KUSNADI	DT HANvan 220	D	D	D	D	N	N	N	N	OFF	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N
86	FAJRI ISLAMI	DT HANVAN 220	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D
87	ANDIKA SAPUTRA	DT HANVAN 221	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N	N
88	YOGI ANDRIAN	DT HANVAN 221	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D
89	TASRIANTO	DT HANVAN 222	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	CR	CR
90	RAHMAD DIANSAH	DT HANVAN 222	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N
91	BOY DEPRAYANDI	DT HANVAN 223	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N
92	GANDUNG HENDRIYAWAN	DT HANVAN 223	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D
93	EDO RIO OKTARA	DT HANVAN 224	N	N	N	N	N	OFF	D	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	N	N	N	N	N
94	DIKA PRANATA	DT HANVAN 224	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	CR	CR	CR	CR	CR	CR	CR
95	BAYU SYAHPUTRA	DT HANVAN 225	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D
96	SAPRIADI	DT HANVAN 225	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N
97	SUPRIYADI	DT HANVAN 226	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N
98	OKI SAPUTRA	DT HANVAN 226	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D
99	EDI SAPUTRA	DT HANVAN 227	OFF	D	D	D	D	D	D	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	D
100	HENGKI SUDRAJAT	DT HANVAN 227	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N
101	FARHAN NOVYANDRA	DT HANVAN 228	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N
102	ARBY RAMADHAN	DT HANVAN 228	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D
103	JONI	DT HANVAN 229	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF
104	GALIH ARMANDO HR	DT HANVAN 229	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	CR	CR	CR	CR	CR
105	KHAIRONI	DT HANVAN 230	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D
106	KUSNEDI	DT HANVAN 230	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N
107	ROY MARTHEN	DT HANVAN 231	D	D	D	N	N	N	OFF	D	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N
108	POLMA SIJABAT	DT HANVAN 231	CR	CR	CR	CR	I	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D
109	ISMAIL	DT HANVAN 232	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF
110	PENI ANDIKA	DT HANVAN 232	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR
111	MHD. DAI FASAID	DT HANVAN 233	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	CR	CR	CR	CR	CR	CR
112	AGUNG PRANATA	DT HANVAN 233	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D
113	ENDANG KUSMA	DT HANVAN 234	N	N	N	OFF	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	N	N	N	N	N
114	DINO ISYAH PUTRA UTAMA	DT HANVAN 234	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	CR	CR	CR	CR	CR	CR
115	ANDITO SAPUTRA	DT HANVAN 235	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D
116	ANDI IRAWAN	DT HANVAN 235	N	N	N	N	OFF	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	D	N	N	N	N
117	BANGSA PERANGIN-ANGIN	DT HANVAN 236	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D
118	RERI ANDRIONETA	DT HANVAN 236	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF
119	BOKNER GALINGGING	DT HANVAN 237	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D
120	GALLVIN CARLO	DT HANVAN 237	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N
121	SYAFII SIREGAR	DT HANVAN 238	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N
122	RAMA DANI	DT HANVAN 238	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D
123	RIKI SAPUTRA	DT HANVAN 239	CR	CR	CR	CR	CR	I	N	N	N	N	N	OFF	D	D	D	D	D	D	D	D	N	N	N	N	N	OFF	D	D	D	D
124	SANDI WIBOWO	DT HANVAN 239	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N
125	RONI SUPARLI	QUESTER 11 CWE 280	OFF	D	D	D	D	D	D	N	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D
126	FAISAL AMRI	QUESTER 11 CWE 280	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	CR	CR	CR	CR	CR
127	IPIN EFENDI	QUESTER 14 CWE 280	D	N	N	N	N	N	N	OFF	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	D
128	SARIKANDI	QUESTER 28 CWE 280	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N
129	ADI ANUGRAH	QUESTER 28 CWE 280	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D
130	RENKI WIGUNA	QUESTER 29 CWE 280	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N
131	DEDI SYAFRIADI	QUESTER 29 CWE 280	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	CR	CR	CR
132	ZULFAHMI FERNANDO	QUESTER 30 CWE 280	CR	I	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D
133	PEJO DELPISA CANDRA	QUESTER 30 CWE 280	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF
134	JUFRIL	QUESTER 31 CWE 280	CR	CR	CR	CR	CR	CR	CR	I	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF
135	DANIL MUSTAPA HARUN	QUESTER 31 CWE 280	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR
136	MANGARA TUA SIANTURI	QUESTER 32 CWE 280	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N
137	MUHAMMAD FAJRI AL MARSY	QUESTER 32 CWE 280	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D
138	PIRDAUS	QUESTER 33 CWE 280	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N
139	DIDIK HERMAWAN	QUESTER 33 CWE 280	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D
140	DANIEL SYAFIKRI	QUESTER 34 CWE 280	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	D	N	N	N	N	N	N	OFF
141	IKNU SETYAWAN	QUESTER 34 CWE 280	CR	CR	CR	CR	CR	I	D	D	D	N	N	N	N	OFF	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D
142	KEPRIANTO	QUESTER 35 CWE 280	I	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D
143	ALDI PRAJANATA	QUESTER 35 CWE 280	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N
144	NASRIANDI	QUESTER 37 CWE 280	N	N	N	N	N	N	OFF	D	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	D	D	D	D	D	N
145	REGI ARMI VOLANDRA	QUESTER 37 CWE 280	CR	CR	CR	CR	CR	I	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D
146	TRI SUSANTO	QUESTER 38 CWE 280	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N
147	ALFI ZULFAROLI	QUESTER 38 CWE 280	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	CR	CR
148	DEDI HENDRA	QUESTER 39 CWE 280	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N
149	NANDO EKA PUTRA	QUESTER 39 CWE 280	N	N	N	N	OFF	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	N	N	N	N	N	N	OFF	D	D
150	ROBY KURNIADO	QUESTER 41 CWE 280	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	CR	CR	CR	CR
151	WIDI ASROFI	QUESTER 41 CWE 280	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D
152	MUHAMMAD NUR SOFYAN	QUESTER 44  CWE 280	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF
153	DIAN DAFIT	QUESTER 44  CWE 280	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR
154	M. REJA	QUESTER 45  CWE 280	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N
155	ALTASER	QUESTER 45  CWE 280	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D
156	PANDI ZIKRILLAH	QUESTER 46  CWE 280	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D
157	RHADIUS PUTRA WIRA	QUESTER 46  CWE 280	D	D	D	D	D	D	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	N	N	N	N	N	N	OFF
158	DICKY PRANATA HS	QUESTER 47  CWE 280	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D
159	ALIT PITOYO	QUESTER 47  CWE 280	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N
160	BENITA INDRA	QUESTER 07 CWE 370	D	D	D	D	D	N	N	N	N	N	N	OFF	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D
161	FAISAL	QUESTER 07 CWE 370	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N
162	ARGIANTO	QUESTER 17 CWE 370	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	CR	CR	CR
163	PRIANDI RISKI	QUESTER 17 CWE 370	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N
164	WAWAN GUSTIAN	QUESTER 18 CWE 370	D	D	D	D	D	D	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	CR	CR	CR	CR
165	FITRA RAMADHAN	QUESTER 18 CWE 370	N	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	N	N	N	N	N	N	OFF	D
166	FERY ALDY YANSYA	QUESTER 19 CWE 370	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	CR
167	IRWAN HIDAYAD	QUESTER 19 CWE 370	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D
168	WISNU ADI PARNATA	QUESTER 20 CWE 370	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	D	D	D	N	N	N	N	OFF	D	D	D	D	D	D	D
169	HENDI AFRIKA	QUESTER 20 CWE 370	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N	N	N
170	ARDIANTON	QUESTER 21 CWE 370	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D
171	AHMAD CHAIRUL MUSTOPA	QUESTER 21 CWE 370	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N
172	MAIRIZALDI	QUESTER 22 CWE 370	D	D	D	D	D	D	D	D	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	CR	CR	CR	CR	CR	CR
173	SEPTA NANDA PRAYOGA	QUESTER 22 CWE 370	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N
174	DEDE WAHYUDI	QUESTER 76 CWE 370	N	N	N	N	N	OFF	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	D	N	N	N	N	N
175	ARTA DARMA SYAPUTRA	QUESTER 76 CWE 370	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	CR	CR	CR	CR	CR
176	RONI SAPUTRA	QUESTER 78 CWE 370	CR	CR	CR	CR	CR	I	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N
177	RIDIANTO RODESKA	QUESTER 78 CWE 370	N	OFF	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D
178	MEGI RISMAYANTO	QUESTER 79 CWE 370	D	D	D	D	N	N	N	N	N	N	N	OFF	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D
179	HENDRI	QUESTER 79 CWE 370	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N	N
180	ASHABUL AIFANI	QUESTER 80 CWE 370	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D
181	ANDRE ANDIKA RAMADAN	QUESTER 80 CWE 370	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF
182	ANTON ASPAPERA	QUESTER 81 CWE 370	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D
183	JEMVORA EFIL BREN	QUESTER 81 CWE 370	D	D	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	CR	CR	CR	CR	CR	CR	CR
184	MUSTAFA RASYID	QUESTER 82 CWE 370	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D
185	HERIANTO	QUESTER 82 CWE 370	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	CR	CR	CR
186	MALVIN RIFANDA POHAN	QUESTER 83 CWE 370	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N
187	ALWIS JAYA	QUESTER 83 CWE 370	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D
188	MARDIANTO	QUESTER 84 CWE 370	D	D	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	OFF	D	D	D	D	D	D	CR	CR	CR	CR	CR	CR	CR
189	HELFI NANDA	QUESTER 84 CWE 370	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D
190	EDY JULIWANTO S	QUESTER 85 CWE 370	D	D	N	N	N	N	N	N	OFF	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	N	N	N
191	PROPEL GANDI	QUESTER 85 CWE 370	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D
192	OKI OKTANIO	QUESTER 106 CWE 370	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	CR	CR	CR	CR	CR	CR	CR
193	RAHMAD GUNAWAN	QUESTER 106 CWE 370	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N
194	SANDI BUDI SURYADI	QUESTER 107 CWE 370	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D
195	NANDRO SAGITA	QUESTER 107 CWE 370	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	CR	CR	CR	CR	CR
196	PRIMA MIDIONO	QUESTER 108 CWE 370	CR	CR	CR	I	N	N	N	N	OFF	D	D	D	D	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N
197	BUDI SARWONO	QUESTER 108 CWE 370	N	N	N	OFF	D	D	D	D	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D
198	ARI YAHYA	QUESTER 124 CWE 370	D	D	D	N	N	N	N	N	OFF	D	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D
199	APENDI	QUESTER 124 CWE 370	N	N	OFF	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	N	N	N	N	N	N	N
200	YANDRA APRINALDI	QUESTER 125 CWE 370	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D
201	ROYNALDI	QUESTER 125 CWE 370	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N
202	NURMAN	DT 03 ORANGE	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N
203	DEDE SUMANTRI	DT 03 ORANGE	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D
204	ALFIAN	DT 04 ORANGE	D	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N
205	YULIUS	DT 04 ORANGE	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D
206	JOND ANDRI SYAPUTRA	DT 05 ORANGE	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	OFF	D	D	D	D	D	N
207	ROMA DANI	DT 05 ORANGE	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I
208	BOBI JASTRIADI	DT 63 ORANGE	CR	CR	CR	CR	I	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D
209	JALPION	DT 63 ORANGE	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N	N	N	N	OFF	D	D	D	D	D	D	N	N
210	DITO PUTRA	DT 65 ORANGE	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N
211	ARLIS	DT 65 ORANGE	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D
212	ENNO	DT 66 ORANGE	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR
213	NANDA ADITYA PRATAMA	DT 66 ORANGE	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N
214	DEDI GUSTIAWAN	DT 67 ORANGE	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D
215	AMRIANTO	DT 67 ORANGE	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N
216	MERZA ADE PUTRA	DT 109 ORANGE	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D
217	EGO SAPUTRA	DT 109 ORANGE	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N
218	GIO ANTONI	DT 110 ORANGE	I	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	D	N	N	N	N	N	OFF	D	D	D	D	D	D	N
219	ANDRI	DT 110 ORANGE	N	N	OFF	D	D	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N	N	N	N	N	N	OFF	D
220	ARISMAN	DT 111 ORANGE	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N
221	BORKAT SIREGAR	DT 111 ORANGE	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D
222	M. ROBI YANTO	DT 112 ORANGE	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N
223	ARI KURNIAWAN	DT 112 ORANGE	CR	CR	CR	CR	CR	CR	CR	I	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D
224	RANGGA SYAHPUTRA	DT 114 ORANGE	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N
225	RABILU SANDI	DT 114 ORANGE	N	OFF	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D
226	INDIKA BOBI PRATAMA	DT 115 ORANGE	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR
227	ANDIKA	DT 115 ORANGE	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	D	N	N	N
228	LEARDO YOGI LABENDRA	DT 116 ORANGE	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N
229	ANDI	DT 116 ORANGE	CR	I	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D
230	SUROTO	DT 119 ORANGE	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N
231	PUR WANTO	DT 119 ORANGE	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D
232	SLAMET	DT 120 ORANGE	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	D	N	N	N	N	N
233	JULPAN	DT 120 ORANGE	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D
234	SUTRISNO	DT 121 ORANGE	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D
235	GAPIS SAGITA	DT 121 ORANGE	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N
236	RIFFANDI IHSAN	DT 122 ORANGE	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D
237	MUHAMMAD FAZAL KHAN	DT 122 ORANGE	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N
238	RIO PEBRIAN	DT 123 ORANGE	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N
239	BENNY SAPUTRA	DT 123 ORANGE	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D
240	BENI RAMADANI	DT HINO 01 (68)	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N
241	APRIYADI	DT HINO 01 (68)	D	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	N	N	N	N	N	N	OFF	D	D	D	D
242	HAMID	DT HINO 02 (69)	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N
243	RAHMAT PRIADI	DT HINO 02 (69)	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D
244	SUWANDI HADI S	DT HINO 03 (70)	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D
245	MUHAMMAD FAHREZA AKBAR	DT HINO 03 (70)	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	N
246	DICKY RAMADHANI	DT HINO 05 (72)	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N
247	TRI SEPRINALDI	DT HINO 05 (72)	D	D	D	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	N	N	N	N	N	N	OFF	D	D
248	AHMAD SLAMED	DT FIGHTER 73	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR
249	MUKRI INDRA SAPUTRA	DT FIGHTER 73	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	D	N
250	RISKI RAMADANI	DT FIGHTER 74	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	N	N	N	N	N	OFF	D	D	D	D	D	D	D	D
251	ARIF SYAHFRUDIN	DT FIGHTER 74	N	N	N	N	OFF	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	CR	CR
252	DONES MARTHA ZULPERLIN	DT FIGHTER 75	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N
253	HADI KESUMA	DT FIGHTER 75	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D
254	R. MAMBI	DRIVER DT SPARE	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR
255	NOPRIANDI	DRIVER DT SPARE	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	CR
256	GENTA AULIA GUNTUR	DRIVER DT SPARE	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D
257	ABIL JANUANDA RIZKY	DRIVER DT SPARE	D	D	D	D	D	D	N	N	N	N	OFF	D	D	D	D	D	D	D	D	N	N	N	N	N	N	N	CR	CR	CR	CR
258	JOKO TRIANTO	DRIVER DT SPARE	D	D	D	D	D	D	N	N	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D
259	MUHAMMAD AMIN	DRIVER DT SPARE	OFF	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	N	CR	CR
260	SURIANTO	DRIVER DT SPARE	D	D	D	D	D	N	N	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D
261	ASPARAINI	DRIVER DT SPARE	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	CR	CR	CR	CR	CR	CR
262	RANGGA APRIANZA	DRIVER DT SPARE	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	CR	CR	CR	CR	CR	CR	CR
263	JHONATAN YESA PUTRA	DRIVER DT SPARE	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	D	CR	CR
264	BERKAH ALHADI. S	DRIVER DT SPARE	D	N	N	N	N	N	N	N	OFF	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	N	N
265	OCTO GANDA MARTUA	DRIVER DT SPARE	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N	OFF	D	D	CR	CR	CR	CR	CR	CR
266	SADRI RAMADANI	DRIVER DT SPARE	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	CR	CR	CR	CR
267	NOPRI NADA SAPUTRA	DRIVER DT SPARE	D	D	D	D	D	D	N	N	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D
268	WIDI KURNIAWAN	DRIVER DT SPARE	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR
269	WILLIE HARYAJI MOES	DRIVER DT SPARE	N	N	OFF	D	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR
270	PENI ERWANDI	DRIVER DT SPARE	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	D	D	D	D	N	N	N	N	N	OFF	D	D
271	NANDA SYAHPUTRA	DRIVER DT SPARE	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	CR	CR
272	RANDA	DRIVER DT SPARE	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR
273	BOBI ARTANTO	DRIVER DT SPARE	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR
274	EKA KUSDIANTO	DRIVER DT SPARE	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	CR	CR	CR	CR	CR	CR
275	GRIMALDI	DRIVER DT SPARE	D	D	D	D	D	D	N	N	N	N	N	N	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR	I	D	D	D	N	N
276	REKI HERDANTONI	DRIVER DT SPARE	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	CR
277	AGUNG SUGIHARTO	DRIVER DT SPARE	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D
278	ANGGA ADI PUTRA	DRIVER DT SPARE	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D
279	MUHAMMAD YANI	DRIVER DT SPARE	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	CR	CR	CR
280	MARLANI	DRIVER DT SPARE	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	CR	CR	CR	CR	CR	CR	CR	CR	CR	CR
281	MASDIANSYAH	DRIVER DT SPARE	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D
282	ARISMAN. J	DRIVER DT SPARE	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	OFF	D	D	D	D	D
283	RIO RAFLES SINAGA	DRIVER DT SPARE	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N	N	OFF
284	DIO SYAHPUTRA	DRIVER DT SPARE	D	D	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N
285	SIWIN CANIAGO	DRIVER DT SPARE	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D
286	IRWAN	DRIVER DT SPARE	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N
287	LUTFI ANDRIANTO	DRIVER DT SPARE	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N
288	DENAS ANDIKA ROSZI	DRIVER DT SPARE	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N
289	VITO PRASETYO	DRIVER DT SPARE	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	D	N	N	N	N
290	SELAMET	DRIVER DT SPARE	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D
291	HANNA SETIA GRAHAFFY	DRIVER DT SPARE	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D
292	NANANG MAULANA	DRIVER DT SPARE	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D
293	ANDIKA ARDIAN	DRIVER DT SPARE	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N
294	INDRA BUANA	DRIVER DT SPARE	N	 N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N
295	ALDONI CANDRA	DRIVER DT SPARE	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N
296	JAMAL	DRIVER DT SPARE	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N
297	MIONO WIBOWO	DRIVER DT SPARE	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N
298	JHONI ALPUTRA	DRIVER DT SPARE	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N
299	RANGGA SENARU	DRIVER DT SPARE	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	N
300	KHAIRUL	DRIVER DT SPARE	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N
301	ERISON	DRIVER DT SPARE	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N	N	N
302	JODI WINALDO	DRIVER DT SPARE	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N
303	RIO AFRIADI	DRIVER DT SPARE	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N
304	SUKMA MUHARIANTO	DRIVER DT SPARE	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N
305	ARI PRA SATIO	DRIVER DT SPARE	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF
306	HERI APRIZAL	DRIVER DT SPARE	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N
307	BUDIMAN MARPAUNG	DRIVER DT SPARE	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N
308	SOPIAN HADI	DRIVER DT SPARE	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D	D	N	N
309	HENDI JAI	DRIVER DT SPARE	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N
310	YOGA SABRAN HUDA	DRIVER DT SPARE	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D	D	D	D	D
311	MISGIADI	DRIVER DT SPARE	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	OFF	D	D
312	EKA NOPRIANTO	DRIVER DT SPARE	D	D	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF	D	D	D	D	D	D	N	N	N	N	N	N	N	OFF`;

export const parseManpowerData = (): Driver[] => {
    const lines = rawData.trim().split('\n');
    const drivers: Driver[] = [];

    lines.forEach((line, index) => {
        try {
            const trimmedLine = line.trim();
            if (!trimmedLine) return;

            // The data appears to be consistently tab-separated for the main columns.
            // Splitting by tab is more robust than splitting by any whitespace,
            // as it correctly handles multi-word names and units.
            const parts = trimmedLine.split('\t');

            // A valid line must have an ID, name, unit, and at least one status.
            if (parts.length < 4) {
                console.warn(`Skipping malformed line ${index + 1}: not enough tab-separated parts. Line: "${line}"`);
                return;
            }

            const id = parseInt(parts[0], 10);
            const name = parts[1].trim();
            const unit = parts[2].trim();
            // Some status values have leading/trailing whitespace (e.g., line 294)
            const dailyStatuses = parts.slice(3).map(s => s.trim()) as Status[];
            
            if (isNaN(id) || !name || !unit) {
                console.warn(`Skipping line with invalid data (ID, name, or unit) ${index + 1}: "${line}"`);
                return;
            }

            drivers.push({ id, name, unit, dailyStatuses });

        } catch (error) {
            console.error(`Failed to parse line ${index + 1}: "${line}"`, error);
        }
    });
    return drivers;
};
